# THIS IS A FILE WITH ALL THE SETTINGS
# AND CONSTANT VARIABLES YOU WILL NEED

HEADER = 1024
PORT = 5050
HOST = 'localhost'
ADDR = (HOST, PORT)
FORMAT = 'utf-8'
DISCONNECT_MESSAGE = '!DISCONNECT!'